# Generated by Django 4.2.6 on 2023-10-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_settingwebsite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',)},
        ),
    ]
